openapi: '3.0.0'
info:
  title: Microservice API
  version: '1.0.0'
tags:
  - name: clients
    description: Microservice for clients
paths:
  /houses:
    get:
      tags:
        - clients
      summary: Get user houses
      parameters:
        - name: user_id
          in: query
          description: user ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/House'
    post:
      tags:
        - clients
      summary: Add house
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/House'
        '400':
          description: Bad request
  /houses/{id}:
    get:
      tags:
        - clients
      summary: Get house
      parameters:
        - name: id
          in: path
          description: ID of house
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/House'
        '404':
          description: Not found response
    patch:
      tags:
        - clients
      summary: Update house
      parameters:
        - name: id
          in: path
          description: ID of house
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/House'
        '404':
          description: Not found response
    delete:
      tags:
        - clients
      summary: Deletes a house
      parameters:
        - name: id
          in: path
          description: ID of house
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful response
        '404':
          description: Not found response

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    House:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: string
